INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `anuncios`(`id_responsable`, `texto_anuncio`) VALUES (7,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');

INSERT INTO `especies`(`nombre`) VALUES ('Gos');
INSERT INTO `especies`(`nombre`) VALUES ('Gat');
INSERT INTO `especies`(`nombre`) VALUES ('Peix');
INSERT INTO `especies`(`nombre`) VALUES ('Rosegador');
INSERT INTO `especies`(`nombre`) VALUES ('Ocell');
INSERT INTO `especies`(`nombre`) VALUES ('Conill');
INSERT INTO `especies`(`nombre`) VALUES ('Reptil');

INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (1,'Nana','Perro','Mestizo','2','25');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (2,'Pancho','Perro','Mestizo','3','3');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (3,'Pucho','Perro','Mestizo','5','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (4,'Dana','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (5,'Rocky','Perro','Mestizo','7','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (6,'Bobi','Perro','Mestizo','8','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (7,'Sasi','Perro','Mestizo','9','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (1,'Fosky','Perro','Mestizo','6','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (2,'Rusqi','Perro','Mestizo','7','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (3,'Trusqui','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (4,'Wasimira','Perro','Mestizo','3','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (5,'Wasimara','Perro','Mestizo','2','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (6,'Crou','Perro','Mestizo','1','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (7,'Leila','Perro','Mestizo','5','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (1,'nasti','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (2,'Blusti','Perro','Mestizo','6','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (3,'Misti','Perro','Mestizo','5','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (4,'Alo','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (5,'Garritas','Perro','Mestizo','7','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (6,'Pinchitos','Perro','Mestizo','5','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (7,'Fuego','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (1,'Como tu','Perro','Mestizo','3','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (2,'Dingo','Perro','Mestizo','2','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (3,'Dango','Perro','Mestizo','7','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (4,'Foli','Perro','Mestizo','8','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (5,'Morpheo','Perro','Mestizo','4','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (6,'Neo','Perro','Mestizo','7','20');
INSERT INTO `mascotas`( `id_usuario`, `nombre`, `especie`, `raza`, `edad`, `peso`) VALUES (7,'Mosti','Perro','Mestizo','5','20');

INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (1,2);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (1,3);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (1,4);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (1,5);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (1,6);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (2,1);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (2,3);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (2,4);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (2,5);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (2,6);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (3,1);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (3,2);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (3,4);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (3,5);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (3,6);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (4,1);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (4,2);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (4,3);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (4,5);
INSERT INTO `mascotas_trabajos`(`id_mascota`, `id_trabajo`) VALUES (4,6);

INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Passejador','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Allotjament','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Perruquer','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Entrenador','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Psicòleg','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Ensinistrador','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Veterinari','N');
INSERT INTO `profesiones`(`nombre_profesion`, `restricciones_titulacion`) VALUES ('Fotograf','N');

INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.5211, 2.1123,'Parc Central del Vallès, Barberà del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.52135, 2.12798,'Parc Europa, Barberà del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.5232, 2.12532,'PipiCan Parc Europa, Barberà del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.511, 2.11942,'Parc de Can Gors, Barberà del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.50679, 2.1136,'Pinar Badia, Badia del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.50951, 2.11505,'Plaça 2 de Maig, Badia del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.49725, 2.13053,'Parc de la Clota, Cerdanyola del Vallès', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.53713, 2.1021,'Plaça del Treball, Sabadell', '');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.52959, 2.11402,'Centre Veterinari La Creu, Sabadell', 'Carrer de Clemència Isaura, 8, 08204 Sabadell, Barcelona');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.53119, 2.11645,'Hospital Veterinari VETs, Sabadell', 'Av. de Barberà, 114, 08203 Sabadell, Barcelona');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.55749, 2.09126,'Veterinario Atlanta, Sabadell', 'Carrer Atlanta, 11, 08206 Sabadell, Barcelona');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.52833, 2.11761,'Clínica Veterinaria Natura, Sabadell', 'Ctra. de Barcelona, 200, LOCAL, 08205 Sabadell, Barcelona');
INSERT INTO `sitios_interes`(`lat`, `lon`, `nombre`, `descripcion`) VALUES (41.51381, 2.12688,'Clínica Veterinària General de Barberà (Veterinario)', 'Ronda de ľEst, 40, 38, 08210 Barberà del Vallès, Barcelona');

INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',1);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',2);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',3);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',4);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',5);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',6);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',1);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',2);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',3);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',4);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',5);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',6);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',1);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',2);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',3);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',4);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',5);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',6);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',1);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',2);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',3);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',4);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',5);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',6);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',1);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',2);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',3);
INSERT INTO `solicitudes`( `solicitud`, `id_usuario_solicitado`) VALUES ('Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?',4);

INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (5,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (6,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (1,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (2,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (3,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');
INSERT INTO `trabajos`( `id_responsable`, `acuerdo`) VALUES (4,'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, repellendus sint laudantium vel, explicabo, eligendi libero voluptatum cum dolor vero perferendis nobis beatae recusandae dolorem reiciendis. Itaque voluptas incidunt voluptatem?');

INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (1,2);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (1,3);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (1,4);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (1,5);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (1,6);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (2,1);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (2,3);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (2,4);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (2,5);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (2,6);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (3,1);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (3,2);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (3,4);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (3,5);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (3,6);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (4,1);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (4,2);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (4,3);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (4,5);
INSERT INTO `usuarios_anuncios`(`id_usuario`, `id_anuncio`) VALUES (4,6);

INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,2);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,2);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,3);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,4);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,5);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (1,6);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (2,1);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (2,3);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (2,4);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (2,5);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (2,6);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (3,1);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (3,2);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (3,4);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (3,5);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (3,6);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (4,1);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (4,2);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (4,3);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (4,5);
INSERT INTO `usuarios_mascotas`(`id_usuario`, `id_mascota`) VALUES (4,6);

INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (1,2,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (1,3,"S","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (1,4,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (1,5,"S","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (1,6,"S","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (2,1,"S","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (2,3,"S","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (2,4,"N","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (2,5,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (2,6,"N","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (3,1,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (3,2,"N","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (3,4,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (3,5,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (3,6,"S","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (4,1,"N","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (4,2,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (4,3,"N","Presencial");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (4,5,"N","Online");
INSERT INTO `usuarios_profesiones`(`id_usuario`, `id_profesion`,`titulacion`,`disponibilidad`) VALUES (4,6,"N","Presencial");

INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (1,2);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (1,3);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (1,4);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (1,5);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (1,6);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (2,1);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (2,3);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (2,4);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (2,5);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (2,6);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (3,1);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (3,2);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (3,4);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (3,5);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (3,6);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (4,1);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (4,2);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (4,3);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (4,5);
INSERT INTO `usuarios_trabajos`(`id_usuario`, `id_trabajo`) VALUES (4,6);

